### ISSUE TITLE
[Setting chart] Display setting items wrong design

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#10]
![Screen Shot 2020-12-09 at 6 48 34 PM](https://user-images.githubusercontent.com/44155302/101626354-6c602600-3a4f-11eb-8a03-e9a3125fbb63.png)

**Comment by myvta** [comment]
![Screen Shot 2020-12-09 at 6 48 34 PM](https://user-images.githubusercontent.com/44155302/101626321-5c484680-3a4f-11eb-98ad-eed63dbe9744.png)

**Comment by tvc12** [comment]
@myvta  fixed
