### ISSUE TITLE
Setting chart/ Series: ở Area chart, các lựa chọn drilldown trong phần Series không scroll được.

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#11]
![Screen Shot 2020-12-09 at 6 58 55 PM](https://user-images.githubusercontent.com/44155302/101627470-fa88dc00-3a50-11eb-897b-e54489b11672.png)
![Screen Shot 2020-12-09 at 6 59 10 PM](https://user-images.githubusercontent.com/44155302/101627475-fc529f80-3a50-11eb-8c43-6658b0c0e689.png)
![Screen Shot 2020-12-09 at 6 59 16 PM](https://user-images.githubusercontent.com/44155302/101627476-fd83cc80-3a50-11eb-9515-dfbe351be5f8.png)

**Comment by myvta** [comment]
Ở column chart cũng bị lỗi này

**Comment by tvc12** [comment]
duplicate #8
