### ISSUE TITLE
[Resize chart] Can't resize chart at the bottom of the screen

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#12]
Thao tác: kéo phóng to Line Chart -> không kéo to được.
![Screen Shot 2020-12-09 at 7 08 40 PM](https://user-images.githubusercontent.com/44155302/101628289-2ce70900-3a52-11eb-9236-75ad203e4bbf.png)

**Comment by tvc12** [comment]
@myvta  fixed
