### ISSUE TITLE
[Setting chart] Can't clear text in input

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#13]
Khi xoá hết dòng "Untitle chart" thì dòng text này xuất hiện lại. Phải dùng Ctrl A mới re-name được.

**Comment by myvta** [comment]
Check lại tất cả các thao tác có liên quan đến re-name. 
Re-name cho Horizontal title và Vertical Title đều bị lỗi giống vậy.

**Comment by tvc12** [comment]
@myvta  fixed
