### ISSUE TITLE
[Setting chart] Drilldown Pie: Label Format unaffected when show data is off 

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#14]
1. Thao tác: chọn Label Format -> không hiện menu drilldown. Mong muốn: Nếu chỉ có 1 lựa chọn, thì không để icon drilldown gây nhầm lẫn thao tác của user.

2. Tại sao lại có chữ "Name" phía trước "Percent"? -> Mong muốn: bỏ chữ "Name"

![Screen Shot 2020-12-14 at 4 02 15 PM](https://user-images.githubusercontent.com/44155302/102061596-427b7a80-3e26-11eb-8c36-804e4d0eca32.png)

**Comment by tvc12** [comment]
@HaoCooky97 will fix it.

**Comment by tvc12** [comment]
@myvta Fixed
