### ISSUE TITLE
[Visualization Hint] Sai mũi tên chỉ trục X và Y

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#15]
![Screen Shot 2020-12-15 at 6 21 38 PM](https://user-images.githubusercontent.com/44155302/102208943-aa06f800-3f02-11eb-8ac0-afa7d224a177.png)

**Comment by myvta** [comment]
@tvc12 ơi check lại nhé. Đúng thì: X là Age, Y là revenue

**Comment by tvc12** [comment]
@myvta cái này là ảnh chị, phần này phải nhờ anh quý update lại

**Comment by tvc12** [comment]
dup #17
