### ISSUE TITLE
[Visualization Hint] Bubble chart: thiếu phần chỉ vào Legend.

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#16]
![Screen Shot 2020-12-21 at 5 56 57 PM](https://user-images.githubusercontent.com/44155302/102770049-13c94b00-43b6-11eb-8673-2cf3c4da05ec.png)

**Comment by myvta** [comment]
@tvc12 này là cố tình hay thiếu nè e

**Comment by tvc12** [comment]
dup #17
