### ISSUE TITLE
[Config panel]: Drop area wrong design

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#3]
Sai UI ở các điểm:
1. Kích thước block [Drag& drop] ở config to hơn so với ở filter.
2. Text [Drag& drop] ở config không đúng vị trí center.

![Screen Shot 2020-12-08 at 3 51 27 PM](https://user-images.githubusercontent.com/44155302/101461348-50845380-396d-11eb-9f68-91f1b62d2678.png)

**Comment by tvc12** [comment]
@myvta  fixed
