### ISSUE TITLE
[Dashboard] Thay đổi style thông báo lỗi nodata ở chart

### ISSUE THREAD

**Issue by quydn** [datainsider-co/rocket-bi-web#34]
![Zalo_ScreenShot_14_1_2021_339608](https://user-images.githubusercontent.com/40825615/104542414-0ec68700-5656-11eb-98a6-877dfa877d62.png)

@HaoCooky Thay đổi dùm anh style thông báo no data hoặc lỗi ở chart dashboard như mô tả thiết kế ở trên zeplin nhé. Thanks.

**Comment by tvc12** [comment]
fixed
