### ISSUE TITLE
[Data Builder] Thay đổi Filter/ Sorting -> Các setting của chart vừa tạo bị quay về mặc định: bao gồm các title & các setting khác.

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#39]
![Screen Shot 2021-01-27 at 6 18 59 PM](https://user-images.githubusercontent.com/44155302/105984027-2711b980-60cc-11eb-8cb5-1786ec58ba1d.png)

**Comment by tvc12** [comment]
related #33
