### ISSUE TITLE
Filter in builder not working with NOT IN and NOT EQUAL

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#42]
Này là lỗi bữa chị đã show action cho em coi đó @HaoCooky @tvc12 

1. Tạo ở builder, có dùng filter "not in" (chart có 4 vùng) -> chọn create -> dashboard: chart chỉ còn 2 vùng.
2. Chọn config chart -> không chỉnh sửa gì và chọn Update -> dashboard: chart ra đúng 4 vùng.
3. Cmd+R -> dashboard: chart lại trở về 2 vùng.

![Screen Shot 2021-02-02 at 5 46 58 PM](https://user-images.githubusercontent.com/44155302/106589927-28852b00-657f-11eb-9849-a82e714f1dfb.png)
![Screen Shot 2021-02-02 at 5 47 05 PM](https://user-images.githubusercontent.com/44155302/106589942-2ae78500-657f-11eb-9c07-dda0bae99fe7.png)

**Comment by tvc12** [comment]
@myvta  fixed
