### ISSUE TITLE
[Setting chart] Dropdown setting overlapping

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#8]
1. Dòng Grid line Dash nằm ngoài viền của block.
![Screen Shot 2020-12-08 at 4 33 12 PM](https://user-images.githubusercontent.com/44155302/101467068-6f3a1880-3974-11eb-82f9-9c8fa97d1072.png)

2. Grid line Dash: không scroll được tới cuối menu và khi scroll bị lỗi
![Screen Shot 2020-12-08 at 4 44 13 PM](https://user-images.githubusercontent.com/44155302/101467328-bde7b280-3974-11eb-8677-5df84f78b486.png)

**Comment by tvc12** [comment]
@myvta  fixed

**Comment by myvta** [comment]
Re-check lại tất cả setting có liên quan và fix triệt để nhé. Trong Series, Axis... cũng bị lỗi này.

**Comment by tvc12** [comment]
@myvta fixed
